version: "3"
services:
  db:
    container_name: dependency-observatory-db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dependency_observatory
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    container_name: dependency-observatory-api
    image: mozilla/dependency-observatory
    volumes:
      - ./:/app:z
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:postgres@db/dependency_observatory
      - FLASK_APP=depobs.website.wsgi:app
      - FLASK_ENV=development
      - HOST=0.0.0.0
      - PORT=8000
      - PROCS=4
      - THREADS=1
      - GITHUB_PAT=${GITHUB_AUTH_TOKEN}
      - HIBP_AUTH_TOKEN=${HIBP_AUTH_TOKEN}
    depends_on:
      - db
    links:
      - db
    # ports:
    #   - "8000:8000"
    command: "migrate web-dev"

  format-web:
    build:
      context: web-dev-env/
    container_name: dependency-observatory-js-dev-env
    image: mozilla/dependency-observatory-js-dev-env
    volumes:
      - ./depobs/website/static:/app/static
    command: " --write /app/static/search_page.js /app/static/do.css /app/static/statistics_page.js /app/static/dep_files_report_page.js /app/static/scan_job_logs_page.js"

  # images we build for the worker to run
  node-10:
    build:
      context: scan_envs/
      args:
        - BASE_NAME=node
        - BASE_VERSION=10-buster-slim
    container_name: dependency-observatory-node-10
    image: mozilla/dependency-observatory:node-10
    command: /bin/bash

  node-12:
    build:
      context: scan_envs/
      args:
        - BASE_NAME=node
        - BASE_VERSION=12-buster-slim
    container_name: dependency-observatory-node-12
    image: mozilla/dependency-observatory:node-12
    command: /bin/bash

  rust-1:
    build:
      context: scan_envs/
      args:
        - BASE_NAME=rust
        - BASE_VERSION=1-slim-buster
    container_name: dependency-observatory-rust-1
    image: mozilla/dependency-observatory:rust-1
    command: /bin/bash
