[tool.black]
line-length = 88
target-version = ["py38"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--doctest-modules --ignore=depobs/worker/wsgi.py"
testpaths = [
  "depobs",
  "tests",
]

filterwarnings = "ignore:\"@coroutine\" decorator is deprecated.*:DeprecationWarning"

# compose mounts . into /app and pytest can't write to its default .pytest_cache dir
cache_dir = "/tmp/pytest_cache"

markers = [
    "dlog: tests ported from https://github.com/ahmetb/dlog/blob/master/reader_test.go (deselect with '-m \"not dlog\"')",
    "unit: tests that do not use the DB or APIs (deselect with '-m \"not unit\"')",
]
